### ISSUE TITLE
Test suite fails

### ISSUE THREAD

**Issue by mdorman** [MichaelXavier/tasty-tap#1]
[Here's a failing NixOS buildlog](http://hydra.cryp.to/build/1114169/nixlog/1/raw).

It would appear the problem is that a file isn't getting included into the tarball.  Looks like you need to add `test/golden/simple.tap` to `extra-source-files`.

**Comment by MichaelXavier** [comment]
Let me know if that fixes it for you and I can cut a release.

**Comment by mdorman** [comment]
Yes, that appears to fix it.

**Comment by MichaelXavier** [comment]
Uploaded.
